# This is a basic workflow to help you get started with Actions

name: Nodejs Runtimes Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: update ca certificates
        run:  sudo update-ca-certificates --fresh  

      - name: Setup
        run: ./tools/travis/setup.sh
      
      - name: Fix Old ansible 
        run: python -m pip install --user ansible==2.8.18

      - name: Build
        run: ./tools/travis/build.sh 

      - name: Deploy
        run: ./tools/travis/deploy.sh

      - name: Test
        run: ./tools/travis/test.sh
